#!/bin/sh

[ -d /build ] && rm -rf build

mkdir build

conan install . -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True --build=missing --output-folder=build

(cd build/;

cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release;

cmake --build .;

make;)
